// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"toy/internal/biz"
	"toy/internal/data"
	"toy/internal/pkg/db"
)

// Injectors from wire.go:

func InitUseCase() (*UseCase, error) {
	sqlDB, err := db.NewDB()
	if err != nil {
		return nil, err
	}
	bomRepo := data.NewBomRepo(sqlDB)
	bomUseCase := biz.NewBomUseCase(bomRepo)
	useCase, err := NewUseCase(bomUseCase)
	if err != nil {
		return nil, err
	}
	return useCase, nil
}
