// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"week.02/internal/dao"
	"week.02/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	db, err := dao.NewDB()
	if err != nil {
		return nil, nil, err
	}
	daoDao, cleanup, err := dao.New(db)
	if err != nil {
		return nil, nil, err
	}
	serviceService, err := service.New(daoDao)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app, err := NewApp(serviceService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
